//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Expenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Home_Expenses()
        {
            this.Home_Expense_Detail = new HashSet<Home_Expense_Detail>();
        }
    
        public int ID_Home_Expense { get; set; }
        public string Description_Home_Expense { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Home_Expense_Detail> Home_Expense_Detail { get; set; }
    }
}
